version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build:
      context: ./
      dockerfile: ./DockerFile
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-conf:/home/odoo/config
    stdin_open: true

volumes:
  odoo-db-data: