FROM ubuntu:22.04
ENV TZ=America/Argentina/Cordoba

RUN mkdir /var/log/odoo \
 && chmod 777 /var/log/odoo \
 && mkdir /home/odoo && mkdir /home/odoo/config \
 && apt update \
 && apt upgrade -y \
 && apt install -y git wget nodejs npm python3 build-essential libzip-dev python3-dev libxslt1-dev python3-pip libldap2-dev python3-wheel libsasl2-dev python3-venv python3-setuptools node-less libjpeg-dev xfonts-75dpi xfonts-base libpq-dev libffi-dev fontconfig\
 && npm install -g rtlcss \ 
 && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata wkhtmltopdf \
 && mkdir /opt/odoo \ 
 && cd /opt/odoo \
 && git clone https://github.com/odoo/odoo.git --depth 1 --branch 16.0 --single-branch odoo-server \
 && cd /opt/odoo/odoo-server \
 && pip3 install wheel \
 && pip3 install -r requirements.txt
 
# CMD ['/opt/odoo/odoo-server/odoo-bin -c /home/odoo/config/odoo-server.conf']