FROM ubuntu:22.04

RUN mkdir /var/log/odoo \
 && chmod 777 /var/log/odoo \
 && mkdir /home/odoo && mkdir /home/odoo/config \
 && apt update \
 && apt upgrade -y \
 && apt install -y git wget nodejs npm python3 build-essential libzip-dev python3-dev libxslt1-dev python3-pip libldap2-dev python3-wheel libsasl2-dev python3-venv python3-setuptools node-less libjpeg-dev xfonts-75dpi xfonts-base libpq-dev libffi-dev fontconfig\
 && npm install -g rtlcss \ 
 && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_arm64.deb 
#  \
#  && dpkg -i wkhtmltox_0.12.6.1-3.bookworm_arm64.deb 

RUN mkdir /opt/odoo \ 
 && cd /opt/odoo \
 && git clone https://github.com/odoo/odoo.git --depth 1 --branch 16.0 --single-branch odoo-server
 
RUN cd /opt/odoo/odoo-server \
#  && python3 -m venv venv \
#  && source venv/bin/activate \
 && pip3 install wheel \
 && pip3 install -r requirements.txt
#  && deactivate
RUN apt install -y wkhtmltopdf








# CMD ['/bin/bash']